### ISSUE TITLE
Underlights support for Apollo Studio

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [mat1jaczyyy/apollo-studio#252]
### Describe the solution you'd like
I would like to use my underlights plugin for Ableton with apollo, to do so, I need to connect apollo studio with loopmidi and then this midi port (virtual) to Ableton Midi Track.

### Describe alternatives you've considered
I can programm my underlights with midi files, but it will be nice to copy the circular button lights of the Launchpad and get Underlights feedback that corresponds with color and place.

### Your setup
I run Windows 10 (64-bit), Ableton Live 10.1 Suite and the last Apollo studio release

**Comment by mat1jaczyyy** [comment]
Thanks for your suggestion!

We've considered underlights support before, however with the way Apollo's development is headed it's near impossible to support any device which doesn't feature a 8x8 or 10x10 RGB grid, let alone a linear light strip which is not standardized in any way (where each user can make their own the way they want, meaning what code it's running, microcontroller, LED strip and LED count, etc; and even how it's physically set up). Apollo relies heavily on naturally placing LED indexes as they are in reality, which makes working with Launchpads a lot easier, it makes working with any 'flexible' device a lot harder.

Sadly, this is not possible to implement. You'll have to create underlight effects in Ableton Live instead. As for copying the outer row, personally I think you should try be original with the underlight and not just copy your Launchpad, because what's the point of getting the underlight device then? If you must, recreate a part of the effect in Ableton and then copy the output.

Sorry!
