### ISSUE TITLE
Launchpad X Support

### ISSUE THREAD

**Issue by EvanCernetic** [mat1jaczyyy/apollo-studio#280]
So I do not own a launchpad pro or mk2 anymore and switched to midi fighter 64 and have recently have gotten a launchpad x as well. I would love if i were to be able to create my light shows with this plugin on my mf64/lpx in the future??

**Comment by mat1jaczyyy** [comment]
MF64 has a separate issue #237, please check existing issues before submitting duplicates in the future.

We've already started some basic support for the X generation of Launchpads and we can currently detect them, but for now we haven't worked out how to get RGB lights output due to missing documentation. There's also the issue of the new LED positioned in the top right corner of the Launchpad.
