### ISSUE TITLE
Delay Duration knob snaps to bottom

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#3]
Bug: Duration knob has a deadzone when turning the duration down. Jumps straight to "0 blue" when value reaches the minimum of 10.

Reproducing:
Turn the duration knob all the way to the left.

Expected behaviour:
Minimal value at minimum of knob, no deadzone when starting to turn to the left.

Setup: Windows 10 Build 10240

**Comment by vaaski** [comment]
@mat1jaczyyy can you look at this? I'm uncertain how to approach since you basically made the dial scaling logic.

**Comment by mat1jaczyyy** [comment]
@vaaski i think it happens because, when the scaled value [0.0, 1.0] updates, the actual value that recalculates *also* triggers a change in the scaled value that snaps it to the recalculated scaled value. think of it like this:

imagine the only valid values for our dial are 0, 1, 2, 3 and 4. dragging down from 1 would snap to 0, because when the scaled value changes from 0.25 to 0.24, it calculates the actual value as 0, which in turn recalculates the scaled value to 0.0 because it is the lowest scaled value that represents the actual value.

**Comment by vaaski** [comment]
Yes, but that's caused by the "deadzone" up until about this degree right? I think that's what we should get rid of, and I don't know what it's caused by.
![image](https://user-images.githubusercontent.com/17879327/48642805-32420880-e9de-11e8-8939-ea993cb41d3e.png)

**Comment by mat1jaczyyy** [comment]
The "deadzone" doesn't snap it back down because the actual value doesn't change, which doesn't tell your reactive thingy to in turn recalculate the scaled value.

**Comment by vaaski** [comment]
But there shouldn't be a zone where the (calculated) value doesn't change at all right?

**Comment by mat1jaczyyy** [comment]
There should when the exponent is high enough, or when there are simply not enough values. I suggest you try to put my example into practice, it will likely help you find what's causing it. If I'm right, the same behavior can be examined for a jump from 2 to 1.

**Comment by mat1jaczyyy** [comment]
Oddly enough, this issue exists in the new UI as well. Low priority but I will check it out at some point

**Comment by mat1jaczyyy** [comment]
hey @vaaski i fixed your issue
