### ISSUE TITLE
Macros for every group

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [mat1jaczyyy/apollo-studio#326]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Add at least 8 macros to every group, the panel would be expandable, not enabled by default. Like in Ableton MIDI Effect Rack

### Describe alternatives you've considered
Use the global macros for every project. Do not remove the globa MACROS, I can use them for pages or subpages

### Your setup
Windows 10 Pro
Apollo 1.3.1

**Comment by mat1jaczyyy** [comment]
What exactly would this achieve? Controls can't be macro mapped. How would you check for a specific Group's Macro?

**Comment by YarostheLaunchpadder** [comment]
What can be mapped?

**Comment by mat1jaczyyy** [comment]
Really nothing can be mapped directly. Macros are designed to be checked for with a Macro Filter, where the Macro Filter behaves like an "if" statement

**Comment by YarostheLaunchpadder** [comment]
I think its related to #317 but you also should make that every setting could be mapped to a macro

**Comment by mat1jaczyyy** [comment]
Not exactly possible to do at the moment, as device parameters are not standardized in any way. Additionally a lot of them depend on them staying the same throughout the playback process otherwise odd glitches may occur. Switch ramping was the idea which would allow for slightly differing FX based on Macro position, by recording a few states in between.

What you're looking for I believe is a duplicate of #169. Having Macros in Group for you would mean you can automate them, while actually adding a few Macros in there would really do nothing other than raise more questions about how those Macros would be checked for.

**Comment by mat1jaczyyy** [comment]
@YarostheLaunchpadder ?

**Comment by YarostheLaunchpadder** [comment]
Yes, it is related, so let's close this request. Thank you for explaining me this!
