### ISSUE TITLE
Adding sound playback to fully integrate covers into Apollo

### ISSUE THREAD

**Issue by TheJSHuA** [mat1jaczyyy/apollo-studio#329]
### Is your feature request related to a problem? Please describe.
My feature request isn't related to a problem with how Apollo works, but a problem with how Launchpad covers currently work. Apollo is nice since it makes light effects way easier, but we're still stuck with drum rack sampling on Ableton, which I find counterintuitive.

### Describe the solution you'd like
It would be nice if Apollo added a new track (to avoid cluttering tracks with light effects), like an "audio track" that holds samples and plays them back when buttons are pressed. 

### Describe alternatives you've considered
I haven't considered any alternatives since the only software you can use to easily sample launchpad covers is Ableton as of right now.

### Your setup
Windows 10 1903 w/ Apollo 1.3.1

### Additional context
I think this could help the launchpad cover community greatly, adding a more friendly interface for sampling the launchpad, and integrating everything into one project file again. This could also help people who want to start making launchpad covers but are confused by the interface of Live (there's a pretty steep learning curve for cover-making). And, for the people who bought the Launchpad X or Launchpad Mini MK3, it would prevent them from having to buy Live Suite to even make/play covers (due to side buttons used for pages being MIDI control change messages instead of notes)

I do know C# (both .NET Core and Framework) so I could help with programming this feature, but I first want to see the thoughts of the people working on this project. There are some libraries that work for realtime audio playback (i.e [bass](http://www.bass.radio42.com/)) so those could be a good starting point.

**Comment by Consoli0** [comment]
I do _like_ this answer, but even though Ableton Live looks confusing, but with an accurate tutorial, people get the hang of it quickly, don't get me wrong, I'd love to see this!

**Comment by TheLifeGamingYT** [comment]
I support this.

**Comment by rpgaleksy** [comment]
We have talked internally about this a couple of times already. Implementing audio into Apollo basically like developing a whole new software again but with the added difficulty of having it still fit and work together with how Apollo currently function.

For people who just cut up songs or stems and play them file playback might seem like a small thing to add, but you have to support multiple different file formats and their quirks and well as having advanced sampling features that you might not instinctively think of when it comes to sampling.
Additionally, there are things like audio effects that would also need to be implemented since there are people out there who like to do more than just cutting up songs and have effects play live, I included.

Ableton Live is already very good at that since it was specifically made as a DAW in the first place, while the community sort of "hacked together" its way to achieve lightshows etc.
Apollo, being developed specifically with the light aspect in mind, would need to jump through quite a few hoops that aren't always particularly easy to resolve, be it DSP, the design (language) or the overall integration into what is already given.

Maybe in the (far) future this might be a thing, but it will pose quite a challenge if it does. No promises.

**Comment by mat1jaczyyy** [comment]
Your suggestion is something we've thought of on multiple occasions. We're glad you think Apollo Studio is the future, but sadly we don't see any audio capabilities ever happening.

It's hard for me to write anything up in here without repeating what aleksy said, but I'll try to give it my own take. The core of the issue remains the same: Ableton Live is professional software developed for decades by audio experts. Its DSP is powered by tons of built-in instruments and audio effects, has VST instrument and effect capabilities, and an already existing chain/track routing system.

It'd be a suicide mission to try and reimplement all of that, especially for a hobbyist programmer like I am. You can argue that most Launchpadders don't use any of these, but any above-average Launchpadder will use sidechaining/compression almost constantly, while some more advanced users will like real instruments and proper effects.

Ableton Live already does the job, and it does it really damn well. I don't want to spend years implementing something that's already there and will likely always be better than what I build. Ableton Live even lets you easily handle sample chopping, as it manages all your files and you can simply drag and drop clips from the arrangement. The Lite version is perfectly suitable for most people in this regard, and is bundled for free with every Launchpad, even second-hand as Novation will reimburse licenses for those if contacted.

Why do you think Drum Racks are unintuitive? If you dislike them, you can use Instrument Racks, which gives more of a chain-like feel. You don't provide any sort of alternative for this, how would you like your sampling interface to feel?

I don't think this helps people who are confused with Live at all - if you replace Live's interface with a new one, they'll still be learning the new interface and be confused by it. This has happened already, I know numerous people who accept Apollo Studio is better for light effects but refuse to switch over in fear of having to learn a new interface.

Regarding the X / Mini MK3's page swapping being broken, personally I prefer a fix from the other side, the Launchpad's firmware itself. I'm currently trying to reverse engineer the firmware in hopes of fixing it up, but I'm still miles away from getting there. There is a workaround which maps to the Arm button in Ableton Live instead of the Chain Selector (1 Track per page), but I agree it's not nice.

We're happy you want to contribute, but I think your efforts are better spent towards existing issues. I will close this issue because I'm sure this won't happen, though I'll keep the discussion open here as I'd love to hear your thoughts regarding my views on the problem.

**Comment by TheJSHuA** [comment]
I understand what you guys mean, didn't really think of it that way before. Thanks for the insight. And yeah, the firmware on the X and MK3 should be fixed. I just saw it as Novation doesn't really care to fix it. The Drum Rack interface I just find kind of weird, I didn't word it correctly in the issue. I just feel it would be nicer to have the launchpad fully laid out in one window (the drum rack is laid out very similarly, but in grids of 4x4). Again, thanks for the insight and comments!

**Comment by mat1jaczyyy** [comment]
Novation doesn't care at all, especially as the whole Launch team has been replaced recently.

Regarding Drum Racks, another case of us "hacking together" stuff with Ableton Live, they were intended for APCs and such, not 8x8 monome-like interfaces :P

Feel free to join us on [Discord](https://discord.gg/8wXs4E) if you wanna chat!
