### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by sc3sc3** [mat1jaczyyy/apollo-studio#364]
Can this application be run on linux ?
If yes then how ?
Thanks.

**Comment by mat1jaczyyy** [comment]
While Apollo itself can technically run on Linux (although never tested), the underlying [RtMidi.Core](https://github.com/micdah/RtMidi.Core) library used for MIDI communication only supports on Windows and macOS. If you run it, you'll likely only have it working with Virtual Launchpads, and no access to physical Launchpads.

Although, I'll leave this up, as I wanted to switch from using RtMidi.Core to using RtMidi directly soon anyway, and at that point I could try to pull off a Linux implementation properly.

**Comment by mat1jaczyyy** [comment]
The auto-updater would also need another platform-specific implementation for Linux.

**Comment by mat1jaczyyy** [comment]
Just merged RtMidi stuff, I'll try check this out sometime in the next few days.

**Comment by mat1jaczyyy** [comment]
@sc3sc3 Check out the [linux](https://github.com/mat1jaczyyy/apollo-studio/tree/linux) branch, I've compiled RtMidi to a shared library and fixed SysEx input. Auto-updating is also disabled and won't be supported on Linux.

For now you'll need to compile it yourself, grab the .NET Core 3.1 SDK and simply run `dotnet run` to debug, or `dotnet publish -r linux-x64 -c Release` to publish a build. Please don't actually make proper projects with this, as the file format changes in an incompatible way between releases.

I'll provide a proper release in the future, although I don't imagine I'll be putting much quality assurance in those builds.

Right now, there are two issues with a Linux release:
1. ALSA doesn't support opening a MIDI port multiple times. Which means you'll have to use Apollo exclusively on your machine, and won't be able to use any other DAW to trigger samples simultaneously. OSX supports this natively, while Windows gets it with Novation's proprietary driver. I have not researched JACK yet and don't know if it does or doesn't have this limitation.
2. Avalonia (the UI framework Apollo uses) still has relatively bad support for Linux compared to OSX and Windows, and there seem to be some issues here and there. Each window opens in the top left corner of the screen instead of being centered at its owner, and a notification displays saying "windowname is ready" displays whenever a window is opened. Might investigate these if the first issue can be solved.

**Comment by sc3sc3** [comment]
Hi @mat1jaczyyy, thanks for making this effort.
I had Apollo running but the firmware was not compatible, so I was sent to https://fw.mat1jaczyyy.com/
The update started, but is currently still running. "apply patches to it in mere seconds." says  https://github.com/mat1jaczyyy/LP-Firmware-Utility, so I guess the update is hanging. 
I'll report back when I get any further

**Comment by mat1jaczyyy** [comment]
@sc3sc3 If Apollo is still running, you're hitting issue 1 and you should close it. Otherwise, make sure your browser supports WebMIDI.

**Comment by sc3sc3** [comment]
I updated the firmware with https://fw.mat1jaczyyy.com/ on a Windows machine, took 2 seconds, worked like a charm. Apollo runs and is functional,  but haven't had time yet to dive into the tutorials. I'll close this bug now. Thanks.

**Comment by mat1jaczyyy** [comment]
I still need to write a publishing script for Linux and merge support into master with a PR

**Comment by mat1jaczyyy** [comment]
Merging as is, there are too many long-term issues with this and too small of a user base to justify a full published release. ALSA doesn't support multiclient use, and Avalonia has windowing issues that make it unpleasant to work with.
