### ISSUE TITLE
Multi device skipping chains

### ISSUE THREAD

**Issue by Pix3l-YT** [mat1jaczyyy/apollo-studio#387]
### Description
Apollo is skipping chains on a multi device.

### To Reproduce
- Create a new project.
- Create a light effect that has 3 chains that does the same thing.
- Create a light effect that has 3 chains on a multi device with the same effect, and does the same thing, with the last one being the same light effect but has a switch device with a layer device set to -100

### Expected behavior
Apollo doesn't skip chain 1 and 3.

### Your setup
Windows 10 Enterprise LTSC (Build 1809), Apollo Version 1.7.0

![2020-09-04-08-20-00](https://user-images.githubusercontent.com/66474423/92189184-47747980-ee88-11ea-9654-22bef7e1d1b3.gif)

**Comment by mat1jaczyyy** [comment]
Can you attach the affected chain?

**Comment by Pix3l-YT** [comment]
> Can you attach the affected chain?

Sure. 
[ok.zip](https://github.com/mat1jaczyyy/apollo-studio/files/5172249/ok.zip)

**Comment by mat1jaczyyy** [comment]
@rpgaleksy test?

**Comment by Pix3l-YT** [comment]
Any progress yet? .<.

**Comment by mat1jaczyyy** [comment]
I'm having exams

**Comment by Pix3l-YT** [comment]
oh ok lmao

**Comment by rpgaleksy** [comment]
@Pix3l-YT Apollo works fine, you built an incorrect chain.
The chain containing the 4-chain Multi triggers on both keys you set in the first Keyfilter, meanwhile the chain containing the 3-chain Multi only goes off on one button.

Including apdev that has the fix in it as well as an optimized version for the whole construct (since you had quite some redundant stuff in there), if you don't understand something feel free to DM me on Discord.
[fix.zip](https://github.com/mat1jaczyyy/apollo-studio/files/5177470/fix.zip)

**Comment by Pix3l-YT** [comment]
Cool, thanks a bunch for the fix! Cheers! 🍻

**Comment by mat1jaczyyy** [comment]
thanks aleks
