### ISSUE TITLE
A page device integrated into Apollo

### ISSUE THREAD

**Issue by citraxlp** [mat1jaczyyy/apollo-studio#401]
### Is your feature request related to a problem? Please describe.
It is not necessarily a (huge) problem, but it would be something very useful to have. Of the current release (1.8.0), there is no dedicated page device. This meant that creating a page-based Apollo project would require the group, switch, and macro filter plugins. This could be hard for new users to get hold at first. 

### Describe the solution you'd like
The best solution would be a dedicated page device. This would provide an easy way for page setup without needing a template. Any UI would be fine, but perhaps just a simplistic one like the multi device where you just press '+' for a new page. A key filter could also be automatically added per page group to define the buttons to swap to that page. 

Switch would still be kept for a similar experience to Twist/Wormhole

### Describe alternatives you've considered
Obviously, a template could be used instead. However, a few caveats include that if someone did not have any person to give the template, setting up would be hard for the first time compared to Ableton's macro. 

A solution for this could be that you could have the option to create a new project from a native apollo template, which includes the pages already setup. 

### Your setup
macOS Catalina 10.15.6
Apollo Studio 1.8.0

**Comment by Brendonovich** [comment]
That's the entire point of the Group, Switch and Macro Filter devices. We have multiple macros that you can use for pages so that you can create custom page layouts, including subpages and using the same effect on multiple pages. Having to use 1 less device isn't really worth it imo compared to the flexibility you have with the current system.
Also, you can enable different 'Auto create (some) Filter in new Group Chain' options to create Key and Macro filters for you in groups. Basically creates a page setup for you.

**Comment by saiman113** [comment]
i have that problem im new on apollo studio and i really dont now how to make page switching.

**Comment by rpgaleksy** [comment]
This is more than redundant.
As was stated the Group+Macrofilter+Switch combination was put in place for maximum flexibility.

For new users who are still learning there also exists a tutorial on how to literally create a basic 8 page project from scratch:
https://youtu.be/ExlrBqfBqqM

Keep in mind that since then there have been some minor naming and UI differences regarding the page system, for more information look up the device reference within the documentation.

**Comment by saiman113** [comment]
i watched that tutorial and make exacly the same but instand the page filter i put in macro filter but this dont work and i dont now hot to working whit switch beacuse of macro and value i dont understand meaning of this

**Comment by rpgaleksy** [comment]
@saiman113 check out the respective paragraphs for Switch and Macro Filter
https://github.com/mat1jaczyyy/apollo-studio/wiki/4.-Device-Reference
If you still don't understand how to set this up feel free to ask in the Apollo Discord server.

**Comment by saiman113** [comment]
thank you for advice now its working
