### ISSUE TITLE
Effects Library

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#412]
### Is your feature request related to a problem? Please describe.
When I'm drawing the fing explosion for the 43248765 time in the project.... I JUST CAN'T THIS MUST END

### Describe the solution you'd like
Preferably an icon somewhere in the apollo window, that just opens up another window with all light effects that i saved. (see screenshot). In this window, you could preview all of the light effects at the same time (for ex looping, or just when you hover at a certain light effect idk) and to speed up things, drag and drop into apollo. Those Light Effects could be stored as a chains or even groups. You could also sort by categories and the path of this folder could be customizable  :D

### Describe alternatives you've considered
Not really an alternative, but i talked in dms about a Light Effects "Store" where you could browse all the avaible light effects on some kind of server (but thats 💰 💰 💰 💰 ) and yeah... just a community thing where you can put your light effects so other people without creativity can just yoink light effects.

### Your setup
noyes

### Additional context
![obraz](https://user-images.githubusercontent.com/43300571/97762750-d2c95e80-1b09-11eb-98bf-769f16f6b09b.png)
i made this in 2 minutes pls

**Comment by Brendonovich** [comment]
Already been discussed in earlier issues and in Discord, @mat1jaczyyy has said to just make a folder in windows and put light effects in there. I'd be down for this feature, but big boss says no

**Comment by WhosPix3l** [comment]
nice setup

**Comment by rpgaleksy** [comment]
That problem is way too generic.  Just use a folder like Brendan suggested and name it in a way that is clear to you.

A solution I could think of is having an option for saving a bitmap-animation-esque preview attached to a chain or device file that can be captured once as an example of how an effect may look like (obviously not all possible options), that is later being played back in a preview-type/preset-browse mode.
Buuut -> way too much work I presume, refer back to the first paragraph.
