### ISSUE TITLE
Driver Checker is wrong.

### ISSUE THREAD

**Issue by rssvxoxo** [mat1jaczyyy/apollo-studio#457]
Win10 1909
Modified the packed DLL (Apollo.dll [since I don't have installed dotnet]) removed the check for Novation's USB driver, working without issues.

Why did I modify the DLL?
Program itself wasn't allow me to use it, was keep saying install the drivers or update etc, but it was up to dated.

![{33ABAF68-BD22-4195-8422-1FD4DB7FD001} png](https://user-images.githubusercontent.com/111044252/209100824-02a653e2-d42f-47ab-9f40-bebc066abb5d.jpg)

**Comment by mat1jaczyyy** [comment]
If you're using Apollo without a DAW, all features will work as expected without the driver. However, some use cases will fail without a good warning such using it with a DAW (multiclient MIDI ports require the driver). Having any other app use the LP MIDI ports (such as Novation Components, fw.mat1jaczyyy.com etc) will also fail.

Since no OS provides an easy API to check what driver is used to run a MIDI port, we fail on startup if that driver doesn't exist in the first place.

So I'm assuming this issue is more about Apollo not picking up that you've actually installed the driver properly, forcing you to resort to such code changes?

**Comment by rssvxoxo** [comment]
Well, after you've said the application would work even without driver, I'm not sure if I installed the driver. I just bought the launchpad yesterday, tried to install driver, but as far I remember something went wrong. Not sure if I deleted the driver or reinstalled it to fix the issue (launchpad couldn't connect to my PC.)

I'm not on my PC right now, so can't check that to see if it's installed or not, but works flawlessly with Ableton & FL Studio & Unitor & Apollo Studio.

**Comment by mat1jaczyyy** [comment]
I see, the drivers suck a lot to manage especially because they're extremely hard to check for, but they provide enough of a difference when using them that we definitely try to force it onto people.

You're most likely running an older version of the driver then which is still functional, however they are prone to BSOD when using multiple launchpads simultaneously so we check for a newer version to hopefully get people to move away from those, had way too many repeat issues about those.

If you're comfortable enough with dnSpy, could you check what `drivers.Max()` returns here?

https://github.com/mat1jaczyyy/apollo-studio/blob/ca751f0fec670d8f0de347a1075b504b9c0ad230/Apollo/Helpers/DriverChecker.cs#L95

Also, I should double check that download link hardcoded in the file, I know Novation have redesigned their website since that was put there so that might be throwing a 404.

**Comment by rssvxoxo** [comment]
Count returns 0 which means I still don't have driver.
When I check devices, I realized that it's not using Novation's driver with that, doesn't work when I install novation's driver aswell.
But works fine with Novation's driver on my laptop w/o issues.

**Comment by mat1jaczyyy** [comment]
Can you try following the steps outlined [here](https://github.com/mat1jaczyyy/apollo-studio/wiki/Extra:-Manually-applying-Novation's-USB-driver-(Windows-only)) to resolve your issue?

**Comment by rssvxoxo** [comment]
> Can you try following the steps outlined [here](https://github.com/mat1jaczyyy/apollo-studio/wiki/Extra:-Manually-applying-Novation's-USB-driver-(Windows-only)) to resolve your issue?
Fixed.
