### ISSUE TITLE
Nesting effects behavior in Group

### ISSUE THREAD

**Issue by ollycrossley** [mat1jaczyyy/apollo-studio#9]
### Description
Paint device fails to produce colour when other chains are added (mostly empty)

### To Reproduce
Create a group, make the first chain a Paint, and then a blank second chain.
Alternatively, you could place a Delay in that second chain and the delay doesn't match the primary
paint value.

### Expected behavior
If the second chain is blank, it goes back to white
If it is a delay, the colour works as you hit the pad, but the delay is white

### Your setup
Windows 10 Home Premium, Apollo (0.0.2)

**Comment by mat1jaczyyy** [comment]
This is intended behavior. The second chain runs at the same time as the first one, and since it happens right after the first one is processed, it draws over the first one. You will exhibit similar behavior by making Chain 0 empty and putting Paint on Chain 1, the color from Chain 1 will be drawn.

I'm not sure as to what you mean by the expected behavior, seems like you're just repeating what's happening right now? Not sure what you want it to do; the Group simply branches the incoming signal into all the Chains at the same time.

**Comment by OllyTheCrosslop** [comment]
I'll re-adjust my post. May have mead a slight error...
